services:
  - type: web
    name: survey-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: >
      bash -c "
        python backend/manage.py migrate &&
        gunicorn core.wsgi:application --chdir backend
      "

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11

    # Optionally set other environment variables for your app, e.g., database or secret keys.
    # - key: DATABASE_URL
    #   value: "your-database-url"
    # - key: SECRET_KEY
    #   value: "your-secret-key"

    # If you're using a database, you can configure that here as well (using the appropriate Render service).
