services:
  - type: web
    name: survey-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: >
      bash -c "
        python backend/manage.py migrate &&
        python backend/manage.py shell -c \"
          from django.contrib.auth import get_user_model;
          User = get_user_model();
          if not User.objects.filter(username='admin').exists():
            User.objects.create_superuser('admin', 'admin@example.com', 'adminpass')
        \" &&
        gunicorn core.wsgi:application --chdir backend
      "

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11
